receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 500
  batch:
    timeout: 10s
    send_batch_size: 512
    send_batch_max_size: 512
  resource:
    attributes:
      - key: cloud.provider
        action: upsert
        value: "${CLOUD_PROVIDER:aws}"
      - key: cloud.platform
        action: upsert
        value: "${CLOUD_PLATFORM:eks}"
      - key: deployment.environment
        action: upsert
        value: "${DEPLOYMENT_ENV:production}"

exporters:
  otlp/
  #: Generic OTLP exporter will use env vars for endpoint and headers

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlp/]
